FROM node:22
# Install PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client

WORKDIR /app
RUN npm i -g bun
COPY package.json bun.lock ./
RUN bun i

COPY docker-entrypoint-dev.sh /usr/local/bin/
COPY inngest-entrypoint-dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint-dev.sh
RUN chmod +x /usr/local/bin/inngest-entrypoint-dev.sh
EXPOSE 4983
COPY . .
ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dev.sh"]
# ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dev.sh", "/usr/local/bin/inngest-entrypoint-dev.sh"]
CMD ["bun", "run", "dev:local"]


# FROM oven/bun:1

# # Install PostgreSQL client (Debian-based Bun image)
# RUN apt-get update && apt-get install -y postgresql-client

# WORKDIR /app

# COPY package.json bun.lockb ./
# # Use bun instead of npm
# RUN bun install

# COPY docker-entrypoint-dev.sh /usr/local/bin/
# RUN chmod +x /usr/local/bin/docker-entrypoint-dev.sh

# COPY . .
# EXPOSE 4000
# ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dev.sh"]
# # Use bun instead of npm
# CMD ["bun", "run", "dev:local"]